Feature/ui add product
UnexpectedSoftware/openMarket pull request #7
Opened 2017-03-30 20:18 UTC by victuxbb

2017-04-05 09:17 UTC, Arkioner requested changes

2017-04-05 09:17 UTC, Arkioner commented on src/openMarket/user_interface/reducers/index.js
> +  form: formReducer,
we missed to move the merge of reducers of newProduct into the component

2017-04-05 10:12 UTC, victuxbb commented on src/openMarket/user_interface/reducers/index.js
> +  form: formReducer,
:+1:

2017-04-06 07:08 UTC, Arkioner approved these changes

2017-04-11 17:44 UTC, merged